version: "3.4"

services:
  ci: &ci
    build: .
    command: ['composer', 'ci']

  dev: &dev
    <<: *ci
    volumes:
      - ./:/code
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dev-7.4:
    <<: *dev
    build:
      context: .
      args:
        PHP_VERSION: "7.4"
