version: "3.4"

services:
  ci: &ci
    build: .
    command: ['composer', 'ci']

  tests-local: &tests-local
    <<: *ci
    volumes:
      - ./:/code
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tests-local-7.4:
    <<: *tests-local
    build:
      context: .
      args:
        PHP_VERSION: "7.4"
