name: GitHub Actions
on: [ push ]
env:
  APP_IMAGE: "encryption-api-php-client"
  DOCKERHUB_USER: "keboolabot"
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and run tests for PHP 8.2
        run: |
          docker compose run ci

      - name: Build and run tests for PHP 7.4
        run: |
          docker compose run ci
